pr:
  - master

pool:
  vmImage: ubuntu-latest

  variables:
  - group: tofu-variables
  - name: dockerRegistryServiceConnection
    value: 'e0fb0a64-0255-45fe-8a29-eb75fb067e4d'
  - name: imageRepository
    value: 'tofuaccounts'
  - name: containerRegistry
    value: 'acrtofu.azurecr.io'
  - name: dockerfilePath
    value: '**/Dockerfile'
  - name: tag
    value: '$(Build.BuildId)'
        
stages:
  - stage: Builder
    jobs:
      - job: build  
        steps:
          - task: Bash@3
            displayName: 'Collecting IP of the runner'
            name: RunnerIP
            inputs:
              targetType: inline
              script: |
                ipaddress=${curl -s http://ipinfo.io/ip}
                echo "##vso[task.setvariable variable=address;isOutput=true;]$ipaddress"

          - task: Bash@3
            displayName: 'Generating random Postgres Password'
            name: PwdGenerator
            inputs:
              targetType: inline
              script: |
                pgsecret=${echo $RANDOM | md5sum | head -c 20; echo}
                echo "##vso[task.setvariable variable=secret;isOutput=true;]$pgsecret"

          - task: Bash@3
            displayName: 'Preparing the working ARM template for deployment'
            env:
              DB_SECRET: $(secret)
            inputs:
              targetType: inline
              script: |
                enbsubst < test/arm/postgres.value.json > postgres.input.json

          - task: AzureCLI@2
            displayName: 'Installing Postgres'
            name: BuildAssets
            inputs:
              azureSubscription: 'MyARMConnection'
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                az group create --name rg-eas-tofucore-tst --location eastasia
                az deployment group create --name tofu-test-deployment \
                --group rg-eas-tofucore-tst --template tests/arm/postgres.arm.json --values postgres.input.json > arm.output.json
                pgname=${jq -r ".outputs.pdbEntityName.value" arm.output.json}
                echo "##vso[task.setvariable variable=postgresName;isOutput=true;]$pgname"
                echo "##vso[task.setvariable variable=resouceGroup;isOutput=true;]rg-eas-tofucore-tst"

          - task: AzureCLI@2
            displayName: 'Loading Scripted Data'
            name: LoadAssets
            inputs:
              azureSubscription: 'MyARMConnection'
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                az login --allow-no-subscription
                az postgres flexible-server execute --name $(postgresName) \
                --admin-user postgres --admin-password $(secret) \
                --database-name postgres --file-path /test/arm/create_db.sql

          - task: NodeTool@0
            displayName: 'Install Node.JS runtime'
            inputs:
              versionSpec: '16.x'  

          - task: Bash@3
            displayName: "Running Tests"
            env:
              DB_SECRET: $(secret)
            inputs:
              targetType: inline
              script: |
                yarn install
                yarn build
                yarn test:e2e    

          - task: AzureCLI@2
            displayName: "Dismental environment"
            inputs: 
              azureSubscription: 'MyARMConnection'
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                az group delete $(resouceGroup)

          - task: Docker@2
            displayName: "Build and Push"
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: $(tag)               
