app:
  capability:
    - name: maxWorkspacePerAccount
      description: "The number of workspace allowed per account"
      system: true
      value: 1
  env: local
  host: localhost
  name: workspace.core.tofu
  port: 3001
  swagger: 
    path: docs

auth:
  host: localhost:8080
  client: TOFU
  realm: TOFU
  secret: ZgrL9eBMbwaA8vQiwObsRRmiNNQL39FR
  oauth2:
    authServerUrl: http://${auth.host}/auth
    authroizationUrl: http://${auth.host}/auth/realms/${auth.realm}/protocol/openid-connect/auth
    scopes:
      profile: 'OpenID Connect built-in scope: profile'
      email: 'OpenID Connect built-in scope: email'
    redirectUrl: http://${app.host}:3001
  
datasource:
  autoLoadEntities: true
  database: tofu.core.workspace
  entities: ['dist/**/*.model{.ts,.js}']
  host: localhost
  migrations: ['dist/**/migrations/*{.ts,.js}']
  migrationsRun: true
  migrationsTableName: custom_migration_table
  password: postgres
  port: 5432
  synchronize: true
  type: postgres
  username: postgres

exchange:
  host: localhost
  password: tofuadmin
  port: 5672
  user: tofu
  exchanges:
    accounts:
      name: account.core.tofu
      capability:
        register: app.capability.register	
    users:
      name: user.core.tofu
      user:
        provisioned: workspaces.user.provisioned


        