name: cd

on:
  push:
    branches:
      - master
  
env: 
  APP_NAME: workspace
  REPO_NAME: acrtofu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: source codebase
        uses: actions/checkout@v3

      - name: logging into ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REPO_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}      

      - name: docker the image
        run: | 
          docker build -t ${{ env.REPO_NAME }}.azurecr.io/tofu${{ env.APP_NAME }}:${{ github.sha }} -t ${{ env.REPO_NAME }}.azurecr.io/tofu${{ env.APP_NAME }}:${{ github.sha }}:latest .
          docker push ${{ env.REPO_NAME }}.azurecr.io/tofu${{ env.APP_NAME }} --all-tags
