name: cd

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: source codebase
        uses: actions/checkout@v3

      - name: docker the image
        run: | 
          docker build \
            -t ${{ env.REPO_NAME }}.azurecr.io/${{ env.app }}:${{ github.sha }} \
            -t ${{ env.REPO_NAME }}.azurecr.io/${{ env.app }}:${{ github.sha }}:latest .          
          docker push ${{ env.REPO_NAME }}.azurecr.io/${{ env.app } --all-tags
