name: cd

on:
  push:
    branches:
      - master      
  
env:
  ACR_REPO: acrtofu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Source code base
        uses: actions/checkout@v3

      - name: Connect to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_REPO }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build container
        run: |
          docker build \
            -t ${{ env.ACR_REPO }}.azurecr.io/tofuworkspace:${github.sha} \
            -t ${{ env.ACR_REPO }}.azurecr.io/tofuworkspace:latest \
          docker push ${{ env.ACR_REPO }}.azurecr.io/tofuworkspace --all-tags
          